name: Check links

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: if ! linkchecker https://linuxcontainers.org/ -f .linkcheckerrc; then cat linkchecker-out.txt; exit 1; fi
